services:
  inventory-db:
    image: postgres:15-alpine
    container_name: inventories_postgres_db
    environment:
      POSTGRES_USER: prueba
      POSTGRES_PASSWORD: Prueb4
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432"
    volumes:
      - inventories-data:/var/lib/postgresql/data
    networks:
      - microservices-net

  inventories-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventories_api
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://inventory-db:5432/inventory_db
      - SPRING_DATASOURCE_USERNAME=prueba
      - SPRING_DATASOURCE_PASSWORD=Prueb4
      - SERVER_PORT=8081
      - PRODUCTS_SERVICE_URL=http://products-api:8080/internal
      - PRODUCTS_SERVICE_API_KEY_HEADER=X-API-Key
      - PRODUCTS_SERVICE_API_KEY_VALUE=$$2a$$12$$QEKgijszxHIM0YLIOluDNumEyJ8e6xzQfHNiUqwUa.48UteHaazJS
    depends_on:
      - inventory-db
    networks:
      - microservices-net

volumes:
  inventories-data:

networks:
  microservices-net:
    external: true
    name: microservices-net