spring.application.name=inventories
#BD
spring.datasource.url=jdbc:postgresql://localhost:5433/inventory_db
spring.datasource.username=prueba
spring.datasource.password=Prueb4
spring.datasource.driver-class-name=org.postgresql.Driver
#Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration
#Puertos
server.port=8081
#Secrets
products.service.url=http://localhost:8080
products.service.apiKeyValue=$2a$12$QEKgijszxHIM0YLIOluDNumEyJ8e6xzQfHNiUqwUa.48UteHaazJS
products.service.apiKeyHeader=X-API-Key
#Resilience4j
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.sliding-window-size=10
resilience4j.circuitbreaker.instances.inventoryCircuitBreaker.failure-rate-threshold=50
resilience4j.retry.instances.inventoryRetry.max-attempts=3
resilience4j.retry.instances.inventoryRetry.wait-duration=1s